name: Auto EUserv

on:
  schedule:
    - cron: '0 0 12 */25 * * *'  # 每25天的中午12点触发一次/运行/执行
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    environment: 
      name: Auto EUserv

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # 指定Python3.x

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Run script
      env:
        EUSERV_USERNAME: ${{ secrets.EUSERV_USERNAME }}
        EUSERV_PASSWORD: ${{ secrets.EUSERV_PASSWORD }}
        TRUECAPTCHA_USERID: ${{ secrets.TRUECAPTCHA_USERID }}
        TRUECAPTCHA_APIKEY: ${{ secrets.TRUECAPTCHA_APIKEY }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}
        MAILPARSER_DOWNLOAD_URL_ID: ${{ secrets.MAILPARSER_DOWNLOAD_URL_ID }}
      run: python Github_Action.py
